# If you only want to install xiaozhi-server in a lightweight way and use only local configuration files,
# you don't need to worry about this file and no changes are required.
# If you want to fetch configuration from manager-api, please read below:
# Copy this file to the xiaozhi-server/data directory. If the data directory does not exist, create it,
# and name the copied file as .config.yaml.
# Note: If there is already a .config.yaml file in the data directory, please delete it first.
# First, start manager-api and manager-web, and register an account. The first registered account will be the administrator.
# Using the administrator account, go to the [Parameter Management] page, find [server.secret], and copy its value.
# Note: Every time you deploy from scratch, server.secret will change.
# Open the .config.yaml file in the data directory and set manager-api.secret to the copied server.secret value.

server:
  ip: 0.0.0.0
  port: 8000
  # Port for the HTTP service, used for visual analysis APIs
  http_port: 8003
  # Visual analysis API address
  # The interface address for visual analysis sent to devices
  # Using the default configuration below, the system will automatically generate the visual recognition address
  # and output it in the startup logs. You can directly visit this address in your browser to confirm it.
  # However, when deploying via Docker or public networks (using SSL or a domain name), this address may not be accurate.
  # Therefore, if deploying with Docker, set vision_explain to the LAN address.
  # If deploying publicly, set vision_explain to the public address.

  vision_explain: http://your ip or domain name:port number/mcp/vision/explain
manager-api:
  # your manager-api address, better to use the LAN address IP
  url: http://127.0.0.1:8002/xiaozhi
  # server.secret your manager-api token, which is the server.secret just copied
  secret: your server.secret value